[package]
name = "dyn_partial_eq"
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["dynamic"]
description = "This crate and it's associatet derive crate enables the user to derive PartialEq for types with dyn objects"
readme = "README.md"

[dependencies]
