[package]
name = "dyn_partial_eq"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["dynamic"]
description = "Two traits to enable PartialEq for types with trait objects as fields. Best used with the derives in dyn_partial_eq_derive"
readme = "README.md"

[dependencies]
